### ISSUE TITLE
[questions] Would this work with 3900x / rx5700xt / broadcom 94352z?

### ISSUE THREAD

**Issue by cyrusauyeungc** [aluveitie/RyzenMacPro#11]
The build looks amazing and I am awaiting for my items to arrive.
Just wondering if the config.plist requires any change if the CPU/GPU and the wifi/bluetooth card is different?
thanks!

**Comment by aluveitie** [comment]
Hi, glad you were able to find the parts.
The following changes would be necessary:
- Delete the 3 entries in DeviceProperties regarding GPU and Wifi (although it should work mostly at least the power play table should be deleted to prevent potential damage to the GPU)
- Adapt the TSCSync kext (for 12 instead of 16 cores) or disable (it’s not required to install)
- Same for AGPMInjector kext, that was generated for the VII and is also not required
