### ISSUE TITLE
Thank you for your work！

### ISSUE THREAD

**Issue by SherlockGougou** [aluveitie/RyzenMacPro#2]
I want to assemble a computer based on your hardware list. What should I pay attention to? Looking forward to your reply!

**Comment by aluveitie** [comment]
你好

Maybe I should first give a little background for the selection. My intent was to build a high performance workstation for software development and video transcoding with a small footprint. So I choose the Evolv Shift (NZXTs H1 was not announced yet) which set some limits on the components but not that an issue since I usually play more CPU heavy games anyway.

Regarding the Motherboard, I went with the ASRock since it had Thunderbolt 3 onboard and I wanted to try it out. But current state there is no Hot plug possible (it works though if the device is connected on boot). I did not end up using Thunderbolt at this time and using it to drive my display with a single USB-C cable (thanks to the available DisplayPort In). As far as I read from other people trying to get Thunderbolt working on the Creator ASRocks ACPI implementation and BIOS is lacking in that area to say the least, apparently Gigabyte is better in that regard for Hackintoshes. If I bought it now I'd have to more carefully weight against the Gigabyte X570 I Aorus Pro since it has 2 M.2 slots and active cooling for the first vs DisplayPort In/USB-C on the ASRock.

The Corsair H80i V2 works well enough to cool the Ryzen 3900X, especially with passive power management now available under MacOS. But I needed to order ultra flat Mini-USB heads (https://www.aliexpress.com/item/4000302723088.html?spm=a2g0s.9042311.0.0.46044c4d3C0p1A) to be able to connect it to the internal USB header since there isn't enough clearance on any side to plug the Corsair cable directly. But it's optional anyway as I've connected the Pump to one Header and set it to constant DC, and the Fans to another Header on the motherboard to let the BIOS handle the fan speed before I got them. I just use the connection to control the RGB at the moment.

The Corsair MP600 is really fast and works well, thanks to its heatsink design I could just cut off/shorten 2 fins to fit it with the heatsink on the back side of the motherboard as the GPU mounting is right beside it.

I went with the RX 5500 as it draws less power and the Sapphire one offers dual BIOS (silent/performance) which is nice to have when you can't use software to control it on MacOS. Today I might consider an RX 5600 but so far the RX 5500 is enough for my needs.
The most important consideration here is Length and thickness. The Sapphire Pulse is about 1cm away from the PSU, you could move it a little more to the side for more clearance but this would make it necessary to remove the heatsink on the MP600. The card should be no more than 2 slots in the Evolv Shift to have enough clearance for airflow.

If you go with a different case then many constraints will not apply. The Evolv Shift requires a lot of considerations selecting the components with cooling in mind and more precision while building. I've already customized it a little to improve air flow and as soon as the lockdown is over I'll head over to a laser cutter with the side panels :)

I'll hope this helps you, if you have further questions I'll be happy to answer them.

**Comment by SherlockGougou** [comment]
Thank you very much for your reply!
I thought twice and finally decided to choose the ATX mainboard, because I am a developer(Android App :) ) and I am busy with my work. So I don’t have much time to modify the case, so my hardware list is as follows:
```
Prozessor: AMD Ryzen 9 3900X
Mainboard: GIGABYTE X570 AORUS PRO WIFI (Remove OnBoard-WiFi module, replace with BCM94360CD PCI-E)
Memory: Corsair Vengeance (2x, 16GB) DDR4-3600
Storage: SAMSUNG 960 PRO 512G NVMe M.2 (2x, 512GB, Windows and macOS)
Video Card: Sapphire RX580 8G
Power Supply: CORSAIR RM650x
Case: NTXZ H510
```
The USB boot-disk is ready, now I am waiting for the delivery,hope everything is fine!

Thanks again!

PS:Forgive my machine translation :)

**Comment by aluveitie** [comment]
I see many of Hackintosh builds with that mainboard, should be a solid choice.

Have fun assembling it :)

**Comment by aluveitie** [comment]
Btw, check that you get the newer Rev 1.1 of the Pro Wifi, that one comes with a Thunderbolt header.

**Comment by Murmur2k** [comment]
@SherlockGougou I have the smaller X570 I AORUS PRO WIFI. For WIFI you could go for an NGFF M.2 straight replacement such as BCM94360NG and save a PCI-E slot.

**Comment by SherlockGougou** [comment]
Oh~Dear, I am very happy to tell you, My computer is running fine with hackintosh. I put my EFI file to github.Hope to help others.
https://github.com/SherlockGougou/ryzen-x570-3900x-hackintosh
:)

**Comment by aluveitie** [comment]
Great to hear everything works 👍
