### ISSUE TITLE
Sleep - USB - Catalina

### ISSUE THREAD

**Issue by EarlOfBurton** [aluveitie/RyzenMacPro#8]
Hello,
having sleep USB problems, using 10.15.6. Following  Aleksandar's USB mapping article

When I look into the /System/Library/Extensions/IOUSBHostFamily.kext/Contents/Plugins/AppleUSBHostProperties.kext/Contents/Info.plist file I see that there is no entry for MacPro7,1.
Only those exist: MacPro5,1 - MacPro6,1
Maybe this is the reason I'm struggling with sleep problems regarding USB with Catalina?
I don't understand that, honestly, because MacPro7,1 is the recent cheese grater mac, right? So it should be supported by Catalina...
Am I doing something wrong?

Regards, EarlOfBurton

**Comment by aluveitie** [comment]
Catalina has sleep problems on all X570 (and even some Intel). It only really works if no problematic USB devices are plugged in.

It is going to be better on Big Sur though.

**Comment by EarlOfBurton** [comment]
Ok, thanks.
Are there big things not working on Big Sur?
Is it already a quite safe point to update to the beta?

Should it be possible to go from a running Catalina system based on your OC, run the Beta Installer (from the running catalina os) and hopefully have a booting system after the installation?
Thanks for your help, mate.

**Comment by aluveitie** [comment]
Big Sur was running very stable since Beta 1. But Beta 9 broke HVEC hardware encoding...

I not sure if the config.plist in this has the most recent experimental patches (should so as far as I remember), maybe fetch the latest just to be sure.

Note that Lilu does not yet support userspace patching on Big Sur, so ketxts like the memory notification disabler do not work anymore.

**Comment by EarlOfBurton** [comment]
Thanks for the quick replies, mate.
